### ISSUE TITLE
Struggling to get the script to work

### ISSUE THREAD

**Issue by Isthatyoudave** [brezlord/iDRAC7_fan_control#1]
Ive got the script  in trunas and have edited the file to point to my idrac as stated but it appears to do nothing. The fans are still running at 30% constantly.

Trying to see if I'm missing something. There are no errors or pop ups. 

Any help would be great

**Comment by brezlord** [comment]
Hi, let’s see if we can fix your problem. Can you tell me what dell server your running and the version of TrueNAS.

**Comment by Isthatyoudave** [comment]
Cheers,

I'm on a dell t320 and on the latest truenas core build.

I'm sitting at it now as it happens.

The commands work on their own in the shell and do turn on or off the automatic and manual fan control. I just can't get the script to change anything.

I appreciate you replying.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brezlord** [comment]
I'm still at work. I'll get back to you tomorrow

**Comment by Isthatyoudave** [comment]
Thanks very much.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brezlord** [comment]
Have you created a Cron Job in TrueNAS web GUI. This is what will call the script and run it. Below is my setup.
The Command is the path to your fan_control.sh file
- Command: ./mnt/system/fan_control/fan_control.sh
- Run As User: Root
- Schedule: Custom (*/5 * * * *) Every 5 minutes

**Comment by Isthatyoudave** [comment]
Yeah, it's all set up in Cron job with the command set to my path and ran as root.

It doesn't throw any error but just does nothing.
The fans stay at what they are. I can check the temps and its below where it should take control of the fans.

If I run a fan command in shell I can set it to 20% which is about right for what use it for. The temps never rise.

It's got the correct fan code, and the correct IP address.

Really odd.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brezlord** [comment]
You need to make sure the script is excitable.
Run the following command from the TrueNAS terminal, navigate to the folder that the script resides in.

chmod +x fan_control.sh

then run the script to make sure it works.
./fan_control.sh

**Comment by Isthatyoudave** [comment]
cheers will test this later and get back to you.

Much appreciated


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Isthatyoudave** [comment]
I'm struggling getting the shell to change directory to the data set.

I'm probs doing a school boy error somewhere.

My path is /mnt/Store/Fan_control

What exactly should I be typing to get to that directory in the shell?



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brezlord** [comment]
cd /mnt/Store/Fan_control

**Comment by brezlord** [comment]
`root@truenas-01[~]# cd /mnt/system/fan_control
root@truenas-01[/mnt/system/fan_control]# ls
fan_control.sh
root@truenas-01[/mnt/system/fan_control]# chmod +x fan_control.sh
root@truenas-01[/mnt/system/fan_control]# ./fan_control.sh
Date 16-05-2023 07:22:17
--> iDRAC IP Address: 192.168.10.95
--> Current Inlet Temp: 18
--> Temperature is below 35deg C
--> Disabled dynamic fan control

--> Setting fan speed to 15%

root@truenas-01[/mnt/system/fan_control]#`

**Comment by Isthatyoudave** [comment]
I get
bad interpreter: /bin/bash^M: no such file or directory

Using ls shows the file is there in the directory.

Wonder if the chmod +x isn't doing anything.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brezlord** [comment]
Can please post the commands you are typing to manually run the script.

**Comment by Isthatyoudave** [comment]
Sorry for late reply.

I'm in the directory of the fan_control.sh file

When I type

./fan_control.sh

It states bad interpreter: /bin/bash^M: no such file or directory.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Isthatyoudave** [comment]
I've got it working.

It was to do with the file itself I created it again  making sure it was converted to Unix encoding it must have been saving as a windows file.

I really appreciate you taking the time to answer.

Another question is

I am looking at putting a usb 3.0 card in the del t320 and also a 2.5gb LAN card or a 10gb card.

Do you know which ones would work with the t320?

Thanks.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
