### ISSUE TITLE
Mind accepting a PR

### ISSUE THREAD

**Issue by shoaib42** [brezlord/iDRAC7_fan_control#2]
Thanks a bunch for this script, my T320 is sitting in my bedroom!

I've made some modifications

- cleaned up the if temp then percent to something simpler
- added a new script based off the original, which handles signals
- systemd service, so this starts on OS start and resets at shutdown/reboot

Here is what it does

1. reset manual fan control
2. sleep 60 seconds
3. trap signals
4. Loop start
5. Your stuff pretty much, but added checks for prev fan % and state of fan control
6. every 10 seconds
7. On sigterm or the likes resets manual fan control.

**Comment by brezlord** [comment]
Thanks for the improvements.
